version: '3.7'

services:
  couchdb:
    image: couchdb:3.0.0
    restart: always
    ports:
    - 5984:5984
    volumes:
    - ./data/couchdb:/opt/couchdb/data
    environment:
    - 'COUCHDB_USER=admin'
    - 'COUCHDB_PASSWORD=password'


  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/logs/:/var/log/rabbitmq/
    hostname: rabbit
